### ISSUE TITLE
Object function LessPluginLists has no method 'install' error

### ISSUE THREAD

**Issue by equinusocio** [seven-phases-max/less-plugin-lists#1]
Hi, when i launch my grunt browser-sync task i get this error by using this plugin:

``` javascript
TypeError: Object function LessPluginLists(options) {
>>     this.options = options;
>> } has no method 'install'
>>     at PluginManager.addPlugin (/Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-contrib-less/node_modules/less/lib/less/plugin-manager.js:29:12)
>>     at PluginManager.addPlugins (/Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-contrib-less/node_modules/less/lib/less/plugin-manager.js:19:18)
>>     at Object.parse (/Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-contrib-less/node_modules/less/lib/less/parse.js:34:27)
>>     at Object.render (/Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-contrib-less/node_modules/less/lib/less/render.js:25:18)
>>     at /Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-contrib-less/node_modules/less/lib/less/render.js:16:24
>>     at lib$es6$promise$$internal$$initializePromise (/Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-autoprefixer/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:378:9)
>>     at new lib$es6$promise$promise$$Promise (/Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-autoprefixer/node_modules/postcss/node_modules/es6-promise/dist/es6-promise.js:669:9)
>>     at Object.render (/Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-contrib-less/node_modules/less/lib/less/render.js:15:20)
>>     at compileLess (/Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-contrib-less/tasks/less.js:149:17)
>>     at /Users/mattia.astorino/Repositories/LIN/FRAMEWORK/lin-front-end-framework/node_modules/grunt-contrib-less/tasks/less.js:59:9
```

This is my task configuration:

``` javascript
var lessPlugins = require('less-plugin-lists');

// Less compiler
less: {
            dev: {
                options: {
                    compress: true,
                    yuicompress: true,
                    optimization: 2,
                    cleancss: true,
                    sourceMap: false,
                    sourceMapFilename: 'css/maps/style.css.map',
                    plugins: [ lessPlugins ],
                },
                files: {
                    "css/style.css": "src/main.less"
                }
            }
        },

```

**UPDATE:**
Editing the index.js of this library it work:

``` javascript
var LessPluginLists = ( function( options ){
    return{
        options: options,
        install: function( less, pluginManager ) { // jshint unused: false
            less.functions.functionRegistry
                .addMultiple(require("./functions")(less));
        }
    }
} )( );
```

**Comment by LucaColonnello** [comment]
Try doing this:

``` js
plugins: [ new lessPlugins( ) ],
```

The plugin is a prototypal function, so it must be instantiated.

**Comment by seven-phases-max** [comment]
`require('less-plugin-lists');` returns a function (object constructor) - not an object.
The [proper usage](https://github.com/gruntjs/grunt-contrib-less#usage-examples) would be:

``` js
var Plugin = require('less-plugin-lists');
...
    plugins: [new Plugin()],
...
```

or the same in short:

``` js
...
plugins: [new (require('less-plugin-lists'))()]
...
```

**Comment by equinusocio** [comment]
Thanks to all. @seven-phases-max i suggest you to update the README file with more specific usage instruction because using a simple require('') doesn't work. :+1:

**Comment by seven-phases-max** [comment]
@equinusocio 

>i suggest you to update the README file with more specific usage instruction because using a simple require('') doesn't work.

Well, the readme [links](https://github.com/seven-phases-max/less-plugin-lists#programmatic-usage) to Less plugins programmatic usage in the Less docs (as well as to specific `grunt` and `gulp` [examples](https://github.com/seven-phases-max/less-plugin-lists#using-with-common-less-tools)). So considering the plugin is not declared to be an ordinal `node.js` module but solely a Less plugin, it's assumed one reads those things and does not try to blindly apply typical `require` primitives.

---
And just in case (not related to the `lists` plugin):
```
compress: true,
yuicompress: true,
optimization: 2,
cleancss: true,
```
These 4 options are better to be removed  to avoid confusion and possible problems in future (1st option is currently deprecated and to be disabled soon, and the other three were removed a while ago). For the CSS-output compression use `less-plugin-clean-css` (see same [link] as above for usage example).

**Comment by seven-phases-max** [comment]
> i suggest you to update the README file with more specific usage instruction because using a simple require('') doesn't work.

I'm afraid I'd rather consider to modify [the example in the docs](http://lesscss.org/usage/#plugins-using-a-plugin-in-code) the readme links to (the trick is that while the example uses "simple" `require`, most (if not all) of Less plugins actually do return a constructor instead of an object, so this docs example may be somewhat misleading). And duplicating the same info again and again across various plugin repos is against my principles of not increasing the universe entropy where not necessary, sorry :).

**Comment by stevenvachon** [comment]
@seven-phases-max over a year and no updates anywhere on this subject.

**Comment by seven-phases-max** [comment]
@stevenvachon 

> over a year and no updates anywhere on this subject.

I'm as plain Less user as you, so in this regard I'm asking the same: why nobody commited the corresponding update to the less-docs?

P.S. The docs example problem was later discussed at https://github.com/less/less.js/issues/2915, but no definitive conclusion is developed so far.
