### ISSUE TITLE
Possible to use plugin through `@plugin`?

### ISSUE THREAD

**Issue by adamwathan** [seven-phases-max/less-plugin-lists#5]
Sorry for opening an issue just for question.

Wondering if it's possible to pull in this plugin using Less' `@plugin` feature in any way? I'm working on a framework/library and would love to use the functionality this plugin provides and it would be awesome to be able to do it without needing to educate end users on how to require and add this plugin to their own build system to be able to use the framework.

Thanks!

**Comment by seven-phases-max** [comment]
No. Currently Less `@plugin` feature only supports primitive-nailed-down scripts. Less v3...4 is planned to [unify this](https://github.com/less/less-meta/issues/17).

**Comment by seven-phases-max** [comment]
Closing as not a (plugin) issue.
