### ISSUE TITLE
.for & .for-each with Less 3.x

### ISSUE THREAD

**Issue by TigersWay** [seven-phases-max/less-plugin-lists#8]
Just did a quick test (Windows 10, node v9.8.0, latest pnpm) .for & .for-each give:
 `undefinedError: Rule is not a constructor` under Less 3.0.1.

- Everything else seem to be working fine.
- Everything is working fine with Less 2.7.3

**Comment by seven-phases-max** [comment]
Less 3.x is not supported yet (I plan an updated version in one or two weeks).
